export const MoviesActionsTypes = {
  GET_MOVIES: 'GET_MOVIES',
  GET_MOVIES_START: 'GET_MOVIES_START',
  GET_MOVIES_FINISH: 'GET_MOVIES_FINISH',
  GET_MOVIES_ERROR: 'GET_MOVIES_ERROR',
  SET_CURRENT_REQUEST: 'SET_CURRENT_REQUEST',
  SET_SORT_PARAM: 'SET_SORT_PARAM',
  SET_FILTER_PARAM: 'SET_FILTER_PARAM',
};
