export const filterItems = ['documentary', 'comedy', 'horror', 'crime', 'drama'];

export const sortingItems = ['release date', 'rating'];

export const moviesData = [
  {
    title: '500 Days of Summer',
    rating: '7.7',
    year: '2009',
    imdbID: 'tt1022603',
    poster: 'https://m.media-amazon.com/images/M/MV5BMTk5MjM4OTU1OV5BMl5BanBnXkFtZTcwODkzNDIzMw@@._V1_SX300.jpg',
    runtime: '95 min',
    genre: 'Comedy, Drama, Romance',
    director: 'Marc Webb',
    plot: "An offbeat romantic comedy about a woman who doesn't believe true love exists, and the young man who falls for her.",
  },
  {
    title: 'I Know What You Did Last Summer',
    rating: '5.7',
    year: '1997',
    imdbID: 'tt0119345',
    poster: 'https://m.media-amazon.com/images/M/MV5BZDI4ODJlNGUtNjFiMy00ODgzLWIzYjgtMzgyZTljZDQ2NGZiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    runtime: '101 min',
    genre: 'Horror, Mystery',
    director: 'Jim Gillespie',
    plot: 'Four young friends bound by a tragic accident are reunited when they find themselves being stalked by a hook-wielding maniac in their small seaside town.',
  },
  {
    title: 'The Kings of Summer',
    rating: '7.1',
    year: '2013',
    imdbID: 'tt2179116',
    poster: 'https://m.media-amazon.com/images/M/MV5BMTc3ODA1NTI0MV5BMl5BanBnXkFtZTcwOTE4OTUzOQ@@._V1_SX300.jpg',
    runtime: '95 min',
    genre: 'Adventure, Comedy, Drama',
    director: 'Jordan Vogt-Roberts',
    plot: 'Three teenage friends, in the ultimate act of independence, decide to spend their summer building a house in the woods and living off the land.',
  },
  {
    title: 'Spring, Summer, Fall, Winter... and Spring',
    rating: '8.0',
    year: '2003',
    imdbID: 'tt0374546',
    poster: 'https://m.media-amazon.com/images/M/MV5BZGYxOTRlM2MtNWRjZS00NDk2LWExM2EtMDFiYTgyMGJkZGYyXkEyXkFqcGdeQXVyMTA1NTM1NDI2._V1_SX300.jpg',
    runtime: '103 min',
    genre: 'Drama, Romance',
    director: 'Ki-duk Kim',
    plot: 'A boy is raised by a Buddhist monk in an isolated floating temple where the years pass like the seasons.',
  },
  {
    title: 'I Still Know What You Did Last Summer',
    rating: '4.7',
    year: '1998',
    imdbID: 'tt0130018',
    poster: 'https://m.media-amazon.com/images/M/MV5BYTgwZmFkZmQtZTVjNC00ZTU4LWI4NjItYzdhYTg1ZjkyODZhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    runtime: '100 min',
    genre: 'Horror, Mystery',
    director: 'Danny Cannon',
    plot: 'The murderous fisherman with a hook is back to once again stalk the two surviving teens, Julie and Ray, who had left him for dead, as well as cause even more murder and mayhem, this time at a posh island resort.',
  },
];
